var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/claim/[token]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f804faa6._.js")
R.c("server/chunks/ssr/0438f_next_dist_b4ed20ca._.js")
R.c("server/chunks/ssr/agent-brain_4517dc76._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09d6fe93._.js")
R.c("server/chunks/ssr/[root-of-the-server]__42bfae4e._.js")
R.c("server/chunks/ssr/0438f_next_dist_552d1473._.js")
R.c("server/chunks/ssr/0438f_next_dist_client_components_builtin_global-error_cae8a71b.js")
R.c("server/chunks/ssr/agent-brain_app_layout_tsx_788377ad._.js")
R.c("server/chunks/ssr/0438f_next_dist_client_components_52de71f1._.js")
R.c("server/chunks/ssr/0438f_next_dist_client_components_builtin_forbidden_a1280884.js")
R.c("server/chunks/ssr/0438f_next_dist_client_components_builtin_unauthorized_756049a9.js")
R.c("server/chunks/ssr/agent-brain__next-internal_server_app_claim_[token]_page_actions_df3f205c.js")
R.m(13462)
module.exports=R.m(13462).exports
