// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents/[name]" | "/claim/[token]" | "/dashboard" | "/network"
type AppRouteHandlerRoutes = "/api/agents" | "/api/agents/[name]" | "/api/agents/claim" | "/api/agents/claim/[token]" | "/api/agents/me" | "/api/agents/register" | "/api/brain/directives" | "/api/brain/rotate" | "/api/brain/signals" | "/api/brain/status" | "/api/directives" | "/api/directives/[id]/accept" | "/api/directives/[id]/complete" | "/api/directives/pending" | "/api/network" | "/api/signals" | "/api/signals/tasks" | "/heartbeat.md" | "/skill.json" | "/skill.md"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agents/[name]": { "name": string; }
  "/api/agents": {}
  "/api/agents/[name]": { "name": string; }
  "/api/agents/claim": {}
  "/api/agents/claim/[token]": { "token": string; }
  "/api/agents/me": {}
  "/api/agents/register": {}
  "/api/brain/directives": {}
  "/api/brain/rotate": {}
  "/api/brain/signals": {}
  "/api/brain/status": {}
  "/api/directives": {}
  "/api/directives/[id]/accept": { "id": string; }
  "/api/directives/[id]/complete": { "id": string; }
  "/api/directives/pending": {}
  "/api/network": {}
  "/api/signals": {}
  "/api/signals/tasks": {}
  "/claim/[token]": { "token": string; }
  "/dashboard": {}
  "/heartbeat.md": {}
  "/network": {}
  "/skill.json": {}
  "/skill.md": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
