// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/agents/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/[name]">> = Specific
  const handler = {} as typeof import("../../app/agents/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/claim/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claim/[token]">> = Specific
  const handler = {} as typeof import("../../app/claim/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/network">> = Specific
  const handler = {} as typeof import("../../app/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/[name]">> = Specific
  const handler = {} as typeof import("../../app/api/agents/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/claim/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/claim/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/agents/claim/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/claim">> = Specific
  const handler = {} as typeof import("../../app/api/agents/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/me">> = Specific
  const handler = {} as typeof import("../../app/api/agents/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/register">> = Specific
  const handler = {} as typeof import("../../app/api/agents/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/brain/directives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brain/directives">> = Specific
  const handler = {} as typeof import("../../app/api/brain/directives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/brain/rotate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brain/rotate">> = Specific
  const handler = {} as typeof import("../../app/api/brain/rotate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/brain/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brain/signals">> = Specific
  const handler = {} as typeof import("../../app/api/brain/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/brain/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brain/status">> = Specific
  const handler = {} as typeof import("../../app/api/brain/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/directives/[id]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/directives/[id]/accept">> = Specific
  const handler = {} as typeof import("../../app/api/directives/[id]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/directives/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/directives/[id]/complete">> = Specific
  const handler = {} as typeof import("../../app/api/directives/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/directives/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/directives/pending">> = Specific
  const handler = {} as typeof import("../../app/api/directives/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/directives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/directives">> = Specific
  const handler = {} as typeof import("../../app/api/directives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/network/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/network">> = Specific
  const handler = {} as typeof import("../../app/api/network/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signals">> = Specific
  const handler = {} as typeof import("../../app/api/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signals/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signals/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/signals/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/heartbeat.md/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/heartbeat.md">> = Specific
  const handler = {} as typeof import("../../app/heartbeat.md/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/skill.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/skill.json">> = Specific
  const handler = {} as typeof import("../../app/skill.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/skill.md/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/skill.md">> = Specific
  const handler = {} as typeof import("../../app/skill.md/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
